import type { WalletSet } from "../types/wallet";

const HEADER = `# Generated by walletgenerator.dev
# Development/test wallets only. Do not use for production funds.`;

const EVM_RPC_PLACEHOLDERS = `SEPOLIA_RPC_URL=
BASE_SEPOLIA_RPC_URL=
ARBITRUM_SEPOLIA_RPC_URL=
OPTIMISM_SEPOLIA_RPC_URL=
POLYGON_AMOY_RPC_URL=
BSC_TESTNET_RPC_URL=
AVALANCHE_FUJI_RPC_URL=
MANTLE_SEPOLIA_RPC_URL=
LINEA_SEPOLIA_RPC_URL=
ZKSYNC_SEPOLIA_RPC_URL=`;

export function toEnv(sets: WalletSet[], includeSeedPhrase = true): string {
  const networkMode = sets[0]?.networkMode ?? "testnet";
  const lines: string[] = [HEADER, "", `NETWORK_MODE=${networkMode}`, ""];

  for (const set of sets) {
    const n = set.index;
    lines.push(`# ---- Wallet ${n} ----`);
    if (includeSeedPhrase) {
      lines.push(`WALLET_${n}_SEED_PHRASE="${set.seedPhrase}"`);
    }
    if (set.evm) {
      lines.push(`EVM_PRIVATE_KEY_${n}=${set.evm.privateKey}`);
      lines.push(`EVM_ADDRESS_${n}=${set.evm.address}`);
    }
    if (set.solana) {
      lines.push(`SOLANA_SECRET_KEY_BASE58_${n}=${set.solana.secretKeyBase58}`);
      lines.push(`SOLANA_SECRET_KEY_ARRAY_${n}=[${set.solana.secretKeyArray.join(",")}]`);
      lines.push(`SOLANA_ADDRESS_${n}=${set.solana.address}`);
    }
    if (set.stellar) {
      lines.push(`STELLAR_SECRET_KEY_${n}=${set.stellar.secretKey}`);
      lines.push(`STELLAR_PUBLIC_KEY_${n}=${set.stellar.publicKey}`);
    }
    if (set.xrp) {
      lines.push(`XRP_SEED_${n}=${set.xrp.seed}`);
      if (set.xrp.privateKey) lines.push(`XRP_PRIVATE_KEY_${n}=${set.xrp.privateKey}`);
      lines.push(`XRP_ADDRESS_${n}=${set.xrp.address}`);
    }
    if (set.bitcoin) {
      lines.push(`BITCOIN_WIF_${n}=${set.bitcoin.wif}`);
      lines.push(`BITCOIN_PRIVATE_KEY_HEX_${n}=${set.bitcoin.privateKeyHex}`);
      lines.push(`BITCOIN_ADDRESS_${n}=${set.bitcoin.address}`);
    }
    lines.push("");
  }

  const hasEvm = sets.some((s) => s.evm);
  const hasSolana = sets.some((s) => s.solana);
  const hasStellar = sets.some((s) => s.stellar);
  const hasXrp = sets.some((s) => s.xrp);
  const hasBitcoin = sets.some((s) => s.bitcoin);

  lines.push("# ---- Network configuration ----");
  if (hasEvm) {
    lines.push(EVM_RPC_PLACEHOLDERS);
  }
  if (hasSolana) {
    lines.push("");
    lines.push("SOLANA_NETWORK=" + (networkMode === "mainnet" ? "mainnet-beta" : "devnet"));
    lines.push(
      "SOLANA_RPC_URL=" +
        (networkMode === "mainnet"
          ? "https://api.mainnet-beta.solana.com"
          : "https://api.devnet.solana.com"),
    );
  }
  if (hasStellar) {
    lines.push("");
    lines.push("STELLAR_NETWORK=" + (networkMode === "mainnet" ? "public" : "testnet"));
    lines.push(
      "STELLAR_HORIZON_URL=" +
        (networkMode === "mainnet"
          ? "https://horizon.stellar.org"
          : "https://horizon-testnet.stellar.org"),
    );
  }
  if (hasXrp) {
    lines.push("");
    lines.push("XRPL_NETWORK=" + (networkMode === "mainnet" ? "mainnet" : "testnet"));
    lines.push(
      "XRPL_RPC_URL=" +
        (networkMode === "mainnet"
          ? "wss://xrplcluster.com"
          : "wss://s.altnet.rippletest.net:51233"),
    );
  }
  if (hasBitcoin) {
    lines.push("");
    lines.push("BITCOIN_NETWORK=" + (networkMode === "mainnet" ? "mainnet" : "testnet"));
    lines.push("BITCOIN_ADDRESS_TYPE=p2wpkh");
  }

  return lines.join("\n") + "\n";
}
