import type { WalletSet } from "../types/wallet";

export function toFoundryEnv(sets: WalletSet[]): string {
  const keys = sets.map((s) => s.evm?.privateKey).filter((k): k is string => Boolean(k));
  const lines = [
    "# Generated by walletgenerator.dev",
    "# Development/test wallets only. Do not use for production funds.",
    "",
  ];
  keys.forEach((key, i) => {
    lines.push(`PRIVATE_KEY_${i + 1}=${key}`);
  });
  lines.push(
    "",
    "SEPOLIA_RPC_URL=",
    "BASE_SEPOLIA_RPC_URL=",
    "ARBITRUM_SEPOLIA_RPC_URL=",
    "OPTIMISM_SEPOLIA_RPC_URL=",
    "POLYGON_AMOY_RPC_URL=",
  );
  return lines.join("\n") + "\n";
}

export const FOUNDRY_TOML = `[rpc_endpoints]
sepolia = "\${SEPOLIA_RPC_URL}"
base_sepolia = "\${BASE_SEPOLIA_RPC_URL}"
arbitrum_sepolia = "\${ARBITRUM_SEPOLIA_RPC_URL}"
optimism_sepolia = "\${OPTIMISM_SEPOLIA_RPC_URL}"
polygon_amoy = "\${POLYGON_AMOY_RPC_URL}"

[profile.default]
src = "src"
out = "out"
libs = ["lib"]
`;

export function toFoundry(sets: WalletSet[]): string {
  return (
    toFoundryEnv(sets) +
    "\n# ---- foundry.toml ----\n" +
    FOUNDRY_TOML
  );
}
