import type { WalletSet } from "../types/wallet";

export function toHardhat(sets: WalletSet[]): string {
  const keys = sets.map((s) => s.evm?.privateKey).filter((k): k is string => Boolean(k));
  const keyList = keys.map((k) => `  "${k}"`).join(",\n");

  return `// Generated by walletgenerator.dev
// Development/test wallets only. Do not use for production funds.
import { HardhatUserConfig } from "hardhat/config";
import "@nomicfoundation/hardhat-toolbox";

const PRIVATE_KEYS = [
${keyList}
];

const config: HardhatUserConfig = {
  solidity: "0.8.24",
  networks: {
    hardhat: {
      accounts: PRIVATE_KEYS.map((privateKey) => ({
        privateKey,
        balance: "10000000000000000000000"
      }))
    },
    sepolia: {
      url: process.env.SEPOLIA_RPC_URL || "",
      accounts: PRIVATE_KEYS
    },
    polygonAmoy: {
      url: process.env.POLYGON_AMOY_RPC_URL || "",
      accounts: PRIVATE_KEYS
    },
    arbitrumSepolia: {
      url: process.env.ARBITRUM_SEPOLIA_RPC_URL || "",
      accounts: PRIVATE_KEYS
    },
    optimismSepolia: {
      url: process.env.OPTIMISM_SEPOLIA_RPC_URL || "",
      accounts: PRIVATE_KEYS
    },
    baseSepolia: {
      url: process.env.BASE_SEPOLIA_RPC_URL || "",
      accounts: PRIVATE_KEYS
    }
  }
};

export default config;
`;
}
